### ISSUE TITLE
locking building level and setting buildings to historic

### ISSUE THREAD

**Issue by peterclemenko** [lxteo/Cities-Skylines-Extended-Building-Info#1]
Hey, would it be possible to implement the functionality from the control building level up mod? In addition, could you please implement the ability to check a box in the building info to set it to historic?

**Comment by robbiemu** [comment]
there already is a [building lock mod](http://steamcommunity.com/sharedfiles/filedetails/?id=410535198) — I suppose historic would be a building that, when abandoned, isn't allowed to be rebuilt to use a different model then the one it had before... not sure how to do that yet.
