### ISSUE TITLE
pt translation complete

### ISSUE THREAD

**Issue by robbiemu** [lxteo/Cities-Skylines-Extended-Building-Info#4]
hey emf, please feel free to pull my pt translations .. I've now done all of the PT stuff — there's bound to be some inaccuracies and errors still but, there were plenty in the original english as well. ..I think it is good enough for prime time and can't wait to play it!

**Comment by lxteo** [comment]
Hey, you have to be the one to create the pull request if I'm not mistaken.

**Comment by robbiemu** [comment]
:+1: ooh :) I've not done that before, I'm on it

**Comment by lxteo** [comment]
Oh, you should sync your fork first, some of the changes in the other files getting overwritten.

**Comment by robbiemu** [comment]
I went back into my client and.. I have nothing to sync at this point. so then I browse my fork here (under master, with last commit of "description residential! PT translation is done!") and all the files under `Localization/pt` appear to be up to date. what is the issue you are seeing with my fork?

**Comment by lxteo** [comment]
There should be an option to sync in github? Like this:
http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/ I
think, I am not that familiar with github as well.

**Comment by robbiemu** [comment]
can you come chat with me on gitter and work through this with me? I still dont see any problem you could have.. on my end it said:

# Comparing changes

Choose two branches to see what's changed or to start a new pull request. If you need to, you can also compare across forks.
**base fork:** `lxteo/Cities-Skylines-Extended-Building-Info`  **base:** `master`  ... **head fork:** `robbiemu/Cities-Skylines-Extended-Building-Info`  **compare:** `master`  
**Able to merge.** These branches can be automatically merged.

...
 _19 commits_ _12 files changed_
...

edit: I think I see.. there are changes listed to files outside of the Localization/pt directory, but I never changed them — so my copy of your master needs to be catch up to your changes first, or else I need to localize my pull request to just one directory.. I remember how to do at least the first, but give me some time I have to look it up
